name: Create HACS Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Build and Create Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the ZIP file
        run: |
          cd custom_components
          zip -r ../samsung_modbus_hp.zip samsung_modbus_hp/
          cd ..

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: samsung_modbus_hp.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
